//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Salary { get; set; }
        public int DeptId { get; set; }
        public string Location { get; set; }
    }
}
