//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbadmission
    {
        public int aid { get; set; }
        public int aappid { get; set; }
        public int asid { get; set; }
        public int adid { get; set; }
        public int acid { get; set; }
    
        public virtual tbcourse tbcourse { get; set; }
        public virtual tbdepartment tbdepartment { get; set; }
        public virtual tbstream tbstream { get; set; }
        public virtual tbapplicant tbapplicant { get; set; }
    }
}
