//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcourse
    {
        public tbcourse()
        {
            this.tbadmissions = new HashSet<tbadmission>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
        public Nullable<int> cdid { get; set; }
    
        public virtual ICollection<tbadmission> tbadmissions { get; set; }
        public virtual tbdepartment tbdepartment { get; set; }
    }
}
