//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdepartment
    {
        public tbdepartment()
        {
            this.tbadmissions = new HashSet<tbadmission>();
            this.tbcourses = new HashSet<tbcourse>();
        }
    
        public int did { get; set; }
        public string dname { get; set; }
        public int dsid { get; set; }
    
        public virtual ICollection<tbadmission> tbadmissions { get; set; }
        public virtual ICollection<tbcourse> tbcourses { get; set; }
        public virtual tbstream tbstream { get; set; }
    }
}
