//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbeducation
    {
        public int eid { get; set; }
        public int eappid { get; set; }
        public int yop_10 { get; set; }
        public string board_10 { get; set; }
        public int percent_10 { get; set; }
        public int yop_12 { get; set; }
        public string board_12 { get; set; }
        public int percent_12 { get; set; }
        public int yop_grad { get; set; }
        public string board_grad { get; set; }
        public int percent_grad { get; set; }
    
        public virtual tbapplicant tbapplicant { get; set; }
    }
}
