//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbstream
    {
        public tbstream()
        {
            this.tbadmissions = new HashSet<tbadmission>();
            this.tbdepartments = new HashSet<tbdepartment>();
        }
    
        public int sid { get; set; }
        public string sname { get; set; }
    
        public virtual ICollection<tbadmission> tbadmissions { get; set; }
        public virtual ICollection<tbdepartment> tbdepartments { get; set; }
    }
}
