//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UASDBContext : DbContext
    {
        public UASDBContext()
            : base("name=UASDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbadmin> tbadmins { get; set; }
        public DbSet<tbadmission> tbadmissions { get; set; }
        public DbSet<tbapplicant> tbapplicants { get; set; }
        public DbSet<tbcourse> tbcourses { get; set; }
        public DbSet<tbdepartment> tbdepartments { get; set; }
        public DbSet<tbeducation> tbeducations { get; set; }
        public DbSet<tbstream> tbstreams { get; set; }
    }
}
